# Site settings
title: OpenXT
email:
description: > # this means to ignore newlines until "baseurl:"
  Development toolkit for hardware-assisted security research and appliance integration. Integrity measurement, virtualization, encapsulation and privacy.
baseurl: "/test2" # the subpath of your site, e.g. /blog/
url: "http://openxt.org" # the base hostname & protocol for your site
twitter_username:
github_username: OpenXT
jira_url: https://openxt.atlassian.net
confluence_url: https://openxt.atlassian.net/wiki
googlegroup: openxt

# Build settings
markdown: kramdown
